name: Deploying PELS' website !

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 19
        uses: actions/setup-node@v3
        with:
          node-version: '19.0.1'

      - name: 🔨 Build Project
        run: |
          npm install
          CI=false npm run build
          
      - name: 📂 Deploy to the desired FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ftp.smart-sfax.org
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          server-dir: /pels-insat.ieee.tn/